### ISSUE TITLE
Bounty: Solve specific issues

### ISSUE THREAD

**Issue by naimmustafa** [naimmustafa/front-end-test#1]
### Reward Size in USD
100 USD

## Bounty

dsfsdf

## Acceptance Criteria

sdf

Go to [Mintycode](https://mintycode.io/naimmustafa/front-end-test?action=CREATOR_OFFERING_MODAL&offeringId=cee3a66a-d034-4476-ac61-aaf69a100618&owner=naimmustafa&name=front-end-test&type=BOUNTIES) to approve the Bounty.

    
[![mintycode](https://imageupload.io/ib/LvxMwrPxam1JW9e_1693210482.png)](https://mintycode.io)

**Comment by Mahhheshh** [comment]
@naimmustafa Can you assist me with Task 6?

**Comment by Mahhheshh** [comment]
Well, I cannot claim the bounty, ;(. Stripe doesn't support the country I am in.
